server:
  enabled: true
  port: 2291
docker: true
encryption: "ARGON2"
registry:
  host: "https://cdn.byjoker.de/myjfql/myjfql.json"
  lookup: true
  autoUpdates: false
  output: "MyJFQL.jar"
jline: true
